baseurl: "" # the subpath of your site, e.g. /blog
url: "https://donpusd.org" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Los_Angeles

github_user: donpusd
github_repo: website
    
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-ical-tag
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
future: true

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


collections:
  posts:
    output: true
  events:
    output: true
    
include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed



# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
