#-------------------------------
# General Site Settings

title: DON PUSD
logo: /assets/images/logo_new.png
author: Aditya Mavalankar
description: Diversify Our Narrative PUSD
email: hello@donpusd.org
copyright: Copyright &copy; Diversify Our Narrative PUSD. Designed with ❤️ in San Diego.
ical-url: https://calendar.google.com/calendar/ical/hinca0g27qemtade0d6ojienl0%40group.calendar.google.com/public/basic.ics

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Events, link: '/events'}
- {name: Clubs, link: '/school-clubs'}
- {name: Contact, link: '/contact'}

#-------------------------------
# Google Analytics Section

google-analytics: UA-173623433-1


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Diversify Our Narrative
  hero-subtitle: Poway Unified

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/DiversifyPUSD/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/Diversifyournarrativepusd/"}
- {icon: "ti-twitter", link: "https://www.twitter.com/DiversifyPUSD/"}
- {icon: "ti-email", link: "mailto:hello@donpusd.org"}

#-------------------------------
# About (Section and Page)

# About Section
blurb:
  "We strive to inspire anti-racist ideals in PUSD through diversified curriculum."

mission: "Our mission is to fight to be anti-racist, and encourage a productive dialogue on race and identity within PUSD through the inclusion of racially diverse, anti-racist cirriculum; to promote open-mindedness within the classroom by incorporating diverse viewpoints."

blurb-btn-link: https://join.donpusd.org
blurb-btn-name: Join Today!



# About Page

# Work Process Section
work-process:
  - title : "Form Subcommittees"
    icon : "ti-comments"
    content : "We have three subcommittees: outreach, curriculum literature, and AP courses. In each committee you get to work on projects firsthand!"
    
  - title : "Work with Schools"
    icon : "ti-blackboard"
    content : "We collaborate with the district, alongside clubs formed at each major PUSD high school. Together, we make an impact."
    
  - title : "Social Media"
    icon : "ti-instagram"
    content : "To maximize our impact and ensure our message of educational equity can be successful, we share and publicize everything we do."


# My Team Section
team:
  - title : "Tamara Alsaied"
    school: "MCHS '22"
    image : "assets/images/team/tamara.jpg"
    position : "Co-President"
    
  - title : "Jessica Malvin"
    school: "MCHS '22"
    image : "assets/images/team/jessica.jpg"
    position : "Co-President"
    
  - title : "Aditya Mavalankar"
    school: "RBHS '21"
    image : "assets/images/team/aditya.jpg"
    position : "Director of Finances"

  - title : "Inbar Schwartz"
    school: "MCHS '22"
    image : "assets/images/team/inbar.jpg"
    position : "Director of Outreach"

  - title : "Katie Schwenker"
    school: "MCHS '22"
    image : "assets/images/team/katie.jpg"
    position : "Executive Secretary"
    
  - title : "Sonia Somasundaram"
    school: "MCHS '22"
    image : "assets/images/team/sonia.jpg"
    position : "Director of Academics"

  - title : "Claire Chung"
    school: "RBHS '21"
    image : "assets/images/team/claire.png"
    position : "Director of Logistics"

#-------------------------------
# Services Section

services-title: Our Goals
services:
- {
    name: Diverse Novels,
    icon: ti-book,
    description: 'Our core goal: we want to bring diverse perspectives to the classroom by incorporating diverse texts, primarily.',
    active: true # Add true to select section
  }
- {
    name: Student Advocates,
    icon: ti-pencil,
    description: 'Our club constitutes students from around the district. Our goal is to form the next generation of student activists and advocates.',
    active: true # Add true to select section
  }
- {
    name: Community Connections,
    icon: ti-rocket,
    description: 'We partner with other social organizations, like Black Student Union, to maximize our impacts.',
    active: true # Add true to select section
  }

# About School Clubs Section

asc-title: About School Clubs
asc:
- {
    name: Form Communities,
    icon: ti-hand-open,
    description: 'We want to bring the community closer in our goal of creating student activists and diversifying our education. These clubs are a great way for students to bond!',
    active: true # Add true to select section
  }
- {
    name: Local Events,
    icon: ti-rss,
    description: 'We host events for the local communities! These can be anything from phonebanking to webinars, and eveyone is welcome! To see upcoming events, go to "Events"',
    active: true # Add true to select section
  }
- {
    name: Student Morale,
    icon: ti-face-smile,
    description: 'Our school clubs are able to focus on the unique and diverse student body of each school! We boost morale on campus and provide a safe space for people to share their thoughts.',
    active: true # Add true to select section
  }

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: hello@donpusd.org

# Jekyll Theme: Jekyll Kross
