# config.yml

backend:
  name: git-gateway
  branch: netlify-cms
  
media_folder: '/assets/uploads'
logo_url: '/assets/images/don-logo.png'
      
collections:
  - name: 'posts'
    identifier_field: posts
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    output: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'events'
    identifier_field: events
    label: 'Events'
    folder: '_events/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    output: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Event Title', name: 'title', widget: 'string' }
      - { label: 'Start Date and Time', name: 'date', widget: 'datetime' }
      - { label: 'End Date and Time', name: 'end-time', widget: 'datetime' }
      - {label: "Sign-Up URL", name: "event-url", widget: "string"}
      - { label: 'Event Description', name: 'description', widget: 'markdown' }
